/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-t_prot
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_T_PROT_API_H
#define INCLUDED_T_PROT_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_t_prot_EXPORTS
#define T_PROT_API __GR_ATTR_EXPORT
#else
#define T_PROT_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_T_PROT_API_H */
